version: '3.8'

services:
  app:
    build: .
    container_name: My_Portfolio
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
